namespace PaleLotus.Cryptomus.Net.Exceptions;

/// <summary>Enumerates documented Cryptomus API error codes.</summary>
public enum CryptomusErrorCode
{
    UnknownError = 0,
    Success = 1,
    InvalidRequest = 2,
    InvalidSignature = 3,
    MerchantNotFound = 4,
    MerchantBlocked = 5,
    InvalidApiKey = 6,
    AccessDenied = 7,
    RateLimitExceeded = 8,
    OperationNotAvailable = 9,
    ServiceUnavailable = 10,
    InsufficientBalance = 11,
    InvoiceNotFound = 12,
    InvoiceAlreadyPaid = 13,
    InvoiceExpired = 14,
    InvoiceCancelled = 15,
    InvoiceStatusConflict = 16,
    InvoiceAmountMismatch = 17,
    InvoiceCurrencyMismatch = 18,
    PayoutNotFound = 19,
    PayoutAlreadyProcessed = 20,
    PayoutBlocked = 21,
    WalletNotFound = 22,
    WalletBlocked = 23,
    UnsupportedCurrency = 24,
    UnsupportedNetwork = 25,
    AmountBelowMinimum = 26,
    AmountAboveMaximum = 27,
    DuplicateRequest = 28,
    StaticWalletAlreadyExists = 29,
    RecurringNotFound = 30,
    RecurringAlreadyCancelled = 31,
    RecurringAlreadyExists = 32,
    DiscountNotFound = 33,
    DiscountAlreadyExists = 34,
    AmlRejected = 35,
    AmlVerificationRequired = 36,
    WebhookNotFound = 37,
    WebhookSignatureInvalid = 38,
    WebhookAlreadySent = 39,
    TestModeOnly = 40,
    Maintenance = 41,
    InternalError = 500,
}
